MSP_homepage:
    pattern:  /
    defaults: { _controller: AppBundle:Default:index }
    
MSP_ewallet:
    pattern:  /ewallet
    defaults: { _controller: AppBundle:Default:ewallet }

MSP_transaction:
    pattern:  /transaction
    defaults: { _controller: AppBundle:Default:transaction }

MSP_payment:
    pattern:  /payment
    defaults: { _controller: AppBundle:Default:payment }
    
MSP_customer:
    pattern:  /customer
    defaults: { _controller: AppBundle:Default:customer }

MSP_customer_delivery:
    pattern:  /customer-delivery
    defaults: { _controller: AppBundle:Default:customerDelivery }
    
MSP_shopping_cart:
    pattern:  /shopping-cart
    defaults: { _controller: AppBundle:Default:shoppingCart }
    
MSP_login:
    pattern:  /login
    defaults: { _controller: AppBundle:Default:login }

MSP_logout:
    pattern:  /logout
    defaults: { _controller: AppBundle:Default:logout }
